[package]
name = "nono"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
